apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stok.fullname" . }}-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "stok.labels" . | nindent 4 }}
