apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "stok.fullname" . }}-workspace
rules:
- apiGroups:
  - stok.goalspike.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
