apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stok.fullname" . }}-workspace
  labels:
    app.kubernetes.io/component: workspace
    {{- include "stok.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.workloadIdentity }}
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
    {{- end }}
