before:
  hooks:
    - make unit
builds:
  - id: stok
    env:
    - CGO_ENABLED=0
    ldflags:
    - '-X "github.com/leg100/stok/version.Version={{ .Version }}"'
    - '-X "github.com/leg100/stok/version.Commit={{ .Commit }}"'
    targets:
    - linux_amd64
    - darwin_amd64
archives:
- format: binary
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "leg100/stok:latest"
  - "leg100/stok:{{ .Tag }}"
  skip_push: auto
  dockerfile: build/Dockerfile
  extra_files:
    - build/bin
    - build/_output/bin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
