apiVersion: v1
kind: Pod
metadata:
  name: sh
spec:
  containers:
  - command:
    - sh
    image: leg100/stok:v0.2.10-20-g16a099e-dirty
    imagePullPolicy: Never
    name: sh
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    tty: true
