apiVersion: apps/v1
kind: Deployment
metadata:
  name: stok-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stok-operator
  template:
    metadata:
      labels:
        name: stok-operator
    spec:
      serviceAccountName: stok-operator
      containers:
        - name: stok-operator
          image: leg100/stok-operator:latest
          command:
          - stok-operator
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "stok-operator"
