name: go build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.4.0
        with:
          args: release --rm-dist --snapshot --skip-sign

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GSA_EMAIL }}
          service_account_key: ${{ secrets.GSA_KEY }}

      - name: Run chart-releaser
        uses: ./.github/actions/gcs-helm-charts-action
        with:
          path: charts/stok
          bucket: goalspike-charts
