name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: login to docker hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u leg100 --password-stdin

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.4.0
        with:
          args: release --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: ./github/actions/chart-releaser-action
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
