name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - uses: azure/docker-login@v1
        with:
          username: leg100
          password: "{{ secrets.DOCKERHUB_TOKEN }}"

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.4.0
        with:
          args: release --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.1
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
